from __future__ import annotations

# Local Vietnamese chat lexicon. Keys/values should stay mostly unaccented
# because text_normalizer strips accents before token replacement.

SLANG_MAP: dict[str, str] = {
    "0k": "ok",
    "oke": "ok",
    "oki": "ok",
    "okie": "ok",
    "okla": "ok",
    "okela": "ok",
    "kg": "khong",
    "kh": "khong",
    "k": "khong",
    "ko": "khong",
    "khongg": "khong",
    "khum": "khong",
    "hum": "khong",
    "hong": "khong",
    "hongg": "khong",
    "hok": "khong",
    "hock": "khong",
    "dc": "duoc",
    "dcd": "duoc",
    "duocj": "duoc",
    "duocc": "duoc",
    "dk": "duoc khong",
    "dko": "duoc khong",
    "mik": "minh",
    "m": "minh",
    "tui": "toi",
    "t": "toi",
    "mk": "mat khau",
    "mn": "moi nguoi",
    "ad": "admin",
    "adminn": "admin",
    "own": "owner",
    "ow": "owner",
    "ql": "quan ly",
    "qly": "quan ly",
    "khachh": "khach",
    "nv": "nhan vien",
    "dt": "doanh thu",
    "ds": "doanh so",
    "rv": "review",
    "fb": "feedback",
    "cmt": "comment",
    "rep": "tra loi",
    "ib": "nhan tin",
    "nt": "nhan tin",
    "dv": "dich vu",
    "dd": "dia diem",
    "km": "khuyen mai",
    "vc": "voucher",
    "tk": "tai khoan",
    "stk": "so tai khoan",
    "nghang": "ngan hang",
    "nganhan": "ngan hang",
    "j": "gi",
    "z": "vay",
    "v": "vay",
    "vayyy": "vay",
    "r": "roi",
    "rui": "roi",
    "roii": "roi",
    "lun": "luon",
    "luonn": "luon",
    "qa": "qua",
    "wa": "qua",
    "vl": "qua",
    "gium": "giup",
    "dum": "giup",
    "nhe": "nha",
    "hen": "nha",
    "nghen": "nha",
    "ne": "ne",
    "kk": "cuoi",
    "kkk": "cuoi",
    "haha": "cuoi",
    "hihi": "cuoi",
    "hic": "buon",
    "huhu": "buon",
}

PHRASE_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    (r"\bdoang\s+thu\b", " doanh thu "),
    (r"\bdoanh\s+thuu\b", " doanh thu "),
    (r"\bdanh\s+gai\b", " danh gia "),
    (r"\bdanh\s+giaa\b", " danh gia "),
    (r"\bkhuyen\s+mai\b", " khuyen mai "),
    (r"\bgiam\s+gia\b", " giam gia "),
    (r"\bma\s+giam\b", " ma giam "),
    (r"\btai\s+khoan\s+ngan\s+hang\b", " tai khoan ngan hang "),
    (r"\bmat\s+khau\b", " mat khau "),
    (r"\bnhan\s+vien\b", " nhan vien "),
    (r"\bfront\s*office\b", " front office "),
    (r"\bdat\s+ban\b", " dat ban "),
    (r"\bdat\s+phong\b", " dat phong "),
    (r"\bquet\s+ve\b", " quet ve "),
    (r"\bso\s+do\s+van\s+hanh\b", " so do van hanh "),
    (r"\bcau\s+hinh\s+so\s+do\b", " cau hinh so do "),
)

SOUTHERN_PARTICLES = (
    "nha",
    "nhe",
    "hen",
    "nghen",
    "ne",
    "do",
    "di",
    "coi",
    "coi thu",
)

YOUTH_FILLERS = (
    "kkk",
    "huhu",
    "hoi chan",
    "gap qua",
    "giup tui",
    "cho tui coi",
    "ok hong",
    "duoc hong",
    "nhe ad",
)
